weights: /home/dp/HDDdisk/LYY/yolov5-master-lyy/runs/train/exp4/weights/last.pt
cfg: ''
data: data/cityspace.yaml
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 100
batch_size: 16
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: true
image_weights: false
device: '2'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
num_f: 1
presave_ratio: 0.9
lambda_decay_rate: 1
lambda_decay_epoch: 5
min_lambda_times: 0.01
lambdap: 70.0
decay_pow: 2
epochb: 30
lrbl: 1.0
lr: 0.01
epochs_decay:
- 24
- 30
sum: true
concat: 1
first_step_cons: 1
save_dir: runs/train/exp4
